### PR TITLE
Attempt at hover on tubes

### PR DESCRIPTION
**Pull request by etpinard**
peek 2018-05-31 11-29

Here's a total glsl-noob attempt at making hover on tubes work. I was able to get picking on the surface of the tubes to work (I think at least), but I haven't quite figured out:

- how to project from the tube surface back to the centerline of the tube
- how to grab the position and velocity values at that centerline

cc'ing @kig in case he's willing to help out.

### CODE REVIEW

**Comment by etpinard** [comment]
Actually, after having testing these commits on a few plotly.js mock off https://github.com/plotly/plotly.js/pull/2658/commits/e0ff37f9d9894629771ec31c3912e79c7d705be4, I'm starting to feel more confident about my solution. I think the picked position is correct, but still something seems off with the picked velocity. In the gif below,

peek 2018-06-01 16-14

looks like the norm (computed using picked velocity) in the hover label doesn't match the tube coloring.

**Comment by etpinard** [comment]
> but still something seems off with the picked velocity

Ha right, those `vectors` we pass to `createTubeMesh` aren't the u/v/w values.

**Comment by kig** [comment]
Yeah, there's a hack there where the length of the vector is used to store the divergence. 

Solutions... I was playing with using the raw u/v/w values and passing in the divergence as the w-component of vec4 vectors. Lemme push that

**Comment by kig** [comment]
Maybe this helps, now we're passing in the raw u/v/w values in vectors b6ae149

**Comment by etpinard** [comment]
> Maybe this helps, now we're passing in the raw u/v/w values in vectors b6ae149

This appears to work beautifully. Thanks for your help @kig !

Ok to merge this PR?

**Comment by kig** [comment]
LGTM, merged

**Pull request merged**
